# Generated by Django 5.1.4 on 2024-12-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_incidentcategory_alter_incident_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('research_paper_links', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
